### ISSUE TITLE
`Amp\Parallel\Worker\Internal\TaskSuccess` is not serializabe

### ISSUE THREAD

**Issue by staabm** [amphp/parallel#103]
After I locally changed my amphp/parallel with https://github.com/amphp/parallel/pull/102 I see the following stacktrace:

```
string(298) "Uncaught Amp\Parallel\Sync\SerializationException in worker with message "The given data of type Amp\Parallel\Worker\Internal\TaskSuccess cannot be sent because it is not serializable." and code "0
"; use Amp\Parallel\Worker\TaskFailureException::getOriginalTrace() for the stack trace in the worker"
string(4086) "#0 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\parallel\lib\Sync\ChannelledStream.php(51): Amp\Parallel\Sync\ChannelParser->encode(Object(Amp\Parallel\Worker\Internal\TaskSuccess))
#1 [internal function](0): Amp\Parallel\Sync\ChannelledStream->Amp\Parallel\Sync\{closure}()
#2 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Coroutine.php(60): Generator->current()
#3 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\functions.php(66): Amp\Coroutine->__construct(Object(Generator))
#4 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\parallel\lib\Sync\ChannelledStream.php(55): Amp\call(Closure(C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\parallel\lib\Sync\ChannelledStream.php:49))
#5 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\parallel\lib\Sync\ChannelledSocket.php(47): Amp\Parallel\Sync\ChannelledStream->send(Object(Amp\Parallel\Worker\Internal\TaskSuccess))
#6 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\parallel\lib\Worker\TaskRunner.php(55): Amp\Parallel\Sync\ChannelledSocket->send(Object(Amp\Parallel\Worker\Internal\TaskSuccess))
#7 [internal function](0): Amp\Parallel\Worker\TaskRunner->execute()
#8 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Coroutine.php(105): Generator->send(Object(PhpCsFixer\Linter\TokenizerLintingResult))
#9 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Internal\Placeholder.php(130): Amp\Coroutine->Amp\{closure}(null, Object(Amp\Parallel\Worker\Internal\Job))
#10 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Coroutine.php(110): Amp\Coroutine->resolve(Object(Amp\Parallel\Worker\Internal\Job))
#11 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Internal\Placeholder.php(130): Amp\Coroutine->Amp\{closure}(null, " 1╔  O:32:"Amp\Parallel\Worker\Internal\Job":2:{s:36:" Amp\Parallel\Worker\Internal\
Job id";s:2:"cn";s:38:" Amp\Parallel\Worker\Internal\Job task";O:36:"PhpCsFixer\Linter\PooledLintFileTask":1:{s:42:" PhpCsFixer\Linter\PooledLintFileTask path";s:56:"C:\xampp7.1.4\htdocs\redaxo\redaxo\src\core\
lib\list.php";}}")
#12 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Deferred.php(45): class@anonymous C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Deferred.php0EE102D7->resolve(" 1╔  O:32:"Amp\Parallel\Worker\
Internal\Job":2:{s:36:" Amp\Parallel\Worker\Internal\Job id";s:2:"cn";s:38:" Amp\Parallel\Worker\Internal\Job task";O:36:"PhpCsFixer\Linter\PooledLintFileTask":1:{s:42:" PhpCsFixer\Linter\PooledLintFileTask pat
h";s:56:"C:\xampp7.1.4\htdocs\redaxo\redaxo\src\core\lib\list.php";}}")
#13 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\byte-stream\lib\ResourceInputStream.php(101): Amp\Deferred->resolve(" 1╔  O:32:"Amp\Parallel\Worker\Internal\Job":2:{s:36:" Amp\Parallel\Worker\Internal\Job id
";s:2:"cn";s:38:" Amp\Parallel\Worker\Internal\Job task";O:36:"PhpCsFixer\Linter\PooledLintFileTask":1:{s:42:" PhpCsFixer\Linter\PooledLintFileTask path";s:56:"C:\xampp7.1.4\htdocs\redaxo\redaxo\src\core\lib\li
st.php";}}")
#14 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Loop\NativeDriver.php(192): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}("a", Resource(stream), null)
#15 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Loop\NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array([Resource(stream)]), Array([]), -0.001)
#16 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Loop\Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#17 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Loop\Driver.php(72): Amp\Loop\Driver->tick()
#18 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\Loop.php(84): Amp\Loop\Driver->run()
#19 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\functions.php(191): Amp\Loop::run(Closure(C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\amp\lib\functions.php:184))
#20 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\parallel\lib\Context\Internal\process-runner.php(98): Amp\Promise\wait(Object(Amp\Coroutine))
#21 C:\xampp7.1.4\htdocs\PHP-CS-Fixer\vendor\amphp\parallel\lib\Context\Internal\process-runner.php(116): Amp\Parallel\Context\Internal\{closure}()"
```

Do I read it correctly and the Exception is telling me that `Amp\Parallel\Worker\Internal\TaskSuccess` is not serializable..?

tested on Windows10x64

```
$ php -v
PHP 7.3.0 (cli) (built: Dec  6 2018 02:17:00) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with blackfire v1.24.1~win-x32-zts73, https://blackfire.io, by Blackfire
```

`"amphp/parallel": "^1.3",`

**Comment by trowski** [comment]
`TaskSuccess` couldn't be serialized because the value given to the constructor could not be serialized. `TaskSuccess` is an internal construct for `TaskRunner`.

**Comment by staabm** [comment]
Would it make sense that TaskSuccess itself would throw when $result passed to it is not serializable?

That way the cause of the error would not be wrapped within TaskSuccess and there might be more obvious... wdyt?

**Comment by staabm** [comment]
I am playing arround with a few more existing projects in which I need/try to implant some async stuff within otherwise sync apps.

After doing some refactorings I get again and again to the topic of not serializable tasks/task-results, because e.g. the existing logic which I refactored passed `Exception`s or `SplFileInfo` or similar objects arround.
In a first naive implementation I just refactored things like people are used to in sync context. I learn the hard way that a lot of php-src builtin stuff is not serializable by playing with it :-).

this made me think.. I guess it could make sense/would be helpful if e.g. amp would have a phpstan extension which would point me to my mistakes.. the current trial & error with huge stacktraces is rather painful and not efficient.

**Comment by kelunik** [comment]
@staabm Sounds like a useful addition, do you want to open a separate issue about plugins for static analysis tools?

Do we still need better exception messages for non-serializable types?

**Comment by staabm** [comment]
> Do we still need better exception messages for non-serializable types?

AFAIR amp improved on this front. 

> Sounds like a useful addition, do you want to open a separate issue about plugins for static analysis tools?

Opened a new issue on the amp repos

**Comment by kelunik** [comment]
Thanks! I've transferred the issue to `amphp/parallel`, because it only affects `amphp/parallel`. https://github.com/amphp/parallel/issues/113
