### ISSUE TITLE
Warnings and errors with parallel driver on Windows

### ISSUE THREAD

**Issue by SeriousKen** [amphp/parallel#117]
I'm using PHP 7.4.6 64bit with ext-parallel 1.1.3 on Windows 10 and I'm having a problem with the following code:

``` php
foreach (range(1, 310) as $message) {
    $coroutines[] = call(function () use ($message) {
        return yield enqueue(new MessageTask($message));
    });
}

$result = wait(all($coroutines));
var_dump($result);
```

There are two issues, when the number of coroutines exceeds the max number of workers in the pool I get the following warning:

```
Worker in pool exited unexpectedly with code -1 in C:\Projects\DemoContent\vendor\amphp\parallel\lib\Worker\DefaultPool.php on line 252
```

If I use error suppression on the `enqueue` function things work for ranges less than 310, but at 310 things stop working again with more warnings:

```
Warning: stream_socket_client(): unable to connect to tcp://127.0.0.1:55485 (No connection could be made because the target machine actively refused it.) in C:\Projects\DemoContent\vendor\amphp\parallel\lib\Context\Parallel.php on line 188
```

Then a fatal error.

```
Fatal error: Uncaught Amp\TimeoutException: Operation timed out in C:\Projects\DemoContent\vendor\amphp\amp\lib\functions.php:275
Stack trace:
#0 C:\Projects\DemoContent\vendor\amphp\amp\lib\Loop\NativeDriver.php(122): Amp\Promise\{closure}('ed', NULL)
#1 C:\Projects\DemoContent\vendor\amphp\amp\lib\Loop\Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#2 C:\Projects\DemoContent\vendor\amphp\amp\lib\Loop\Driver.php(72): Amp\Loop\Driver->tick()
#3 C:\Projects\DemoContent\vendor\amphp\amp\lib\Loop.php(95): Amp\Loop\Driver->run()
#4 C:\Projects\DemoContent\vendor\amphp\amp\lib\functions.php(229): Amp\Loop::run(Object(Closure))
#5 C:\Projects\DemoContent\test11.php(16): Amp\Promise\wait(Object(Amp\Internal\PrivatePromise))
#6 {main}

Next Amp\Parallel\Context\ContextException: Starting the process timed out in C:\Projects\DemoContent\vendor\amphp\parallel\lib\Context\Internal\ProcessHub.php:141
Stack trace:
#0 [internal function]: Amp\Parallel\Context\Internal\ProcessHub->Amp\Parallel\Context\Internal\{closure}()
#1 C:\ in C:\Projects\DemoContent\vendor\amphp\parallel\lib\Context\Parallel.php on line 262
```

The code for the message task does nothing special:

``` php
class MessageTask implements Task
{
    protected $message;

    public function __construct($message)
    {
        $this->message = $message;
    }

    public function run(Environment $environment)
    {
        return 'Task number '.$this->message;
    }
}
```

The code works perfectly without any problems if I disable ext-parallel.

**Comment by SeriousKen** [comment]
The only way I've found that works is to use the loop and wrap the enqueue in a Loop::delay

``` php
Loop::run(function () {
    $coroutines = [];

    foreach (range(1, 310) as $count) {
        Loop::delay($count * 10, function () use ($count) {
            $coroutines[] = call(function () use ($count) {
                return yield enqueue(new DummyTask());
            });
        });
    }

    yield $coroutines;
});
```

It looks like ext-parallel needs some time between enqueues, otherwise it tries to do everything in one tick and it crashes.

**Comment by trowski** [comment]
Sorry for not addressing this sooner. I can't reproduce this on *nix, so I'll have to get one of the developers with access to a Windows machine to test this.

Ping @DaveRandom @krakjoe If either of you have time to look at this I'd appreciate it!

**Comment by trowski** [comment]
We've dropped support for ext-parallel as the extension is no longer being developed.
