### ISSUE TITLE
Error in sub-pools/processes inside a pool/process using parallel

### ISSUE THREAD

**Issue by iamsyh** [amphp/parallel#134]
Hello!

I'm trying to run a pool of sub-processes inside another pool of processes using amphp-parallel and the following code of mine keeps failing:

**Main code starting the parent process/pool:-**

`if (database_querySelect($sql,$rows))
                {
                    Loop::run(function () use ($rows, $config_feedDirectory) {

                        $pool = new DefaultPool('50');

                        foreach($rows as $feed) {
                            if (file_exists($config_feedDirectory.$feed["filename"]))
                            {
                                $tasks[] = new Misc('import', $feed);
                            }
                        }

                        $coroutines = [];

                        foreach ($tasks as $index => $task) {
                            $coroutines[] = Amp\call(function () use ($pool, $index, $task) {
                                $result = yield $pool->enqueue($task);
                                return $result;
                            });
                        }

                        $results = yield Amp\Promise\all($coroutines);

                        yield $pool->shutdown();

                    });
                }`

**Code for spawning sub-process/pool:** 

try {
                \Amp\Loop::run(function () use ($all_results) {

                    $pool = new \Amp\Parallel\Worker\DefaultPool('10');

                    foreach ($all_results as $result) {
                        $to_send = array($this->admin_importCallback, $this->admin_importFeed, $this->admin_importLimit, $this->feed, $result);
                        $tasks[] = new Misc('temp_sub_process', $to_send);
                    }

                    $coroutines = [];

                    foreach ($tasks as $index => $task) {
                        $coroutines[] = \Amp\call(function () use ($pool, $task) {
                            $all_results = yield $pool->enqueue($task);
                            return TRUE;
                        });
                    }

                    $results = yield \Amp\Promise\all($coroutines);

                    yield $pool->shutdown();

                });
            } catch(MultiReasonException $error) {
                print_r($error->getReasons());
                return FALSE;
            }

The above fails. However! When I changed the code for the parent process/pool to the following:-

`if (database_querySelect($sql,$rows))
                {
                    Loop::run(function () use ($rows, $config_feedDirectory) {

                        $pool = new DefaultPool('50');

                        foreach($rows as $feed) {
                            if (file_exists($config_feedDirectory.$feed["filename"]))
                            {
                                $tasks[] = new Misc('import', $feed);
                            }
                        }

                        $coroutines = [];

                        foreach ($tasks as $index => $task) {
                            $coroutines[] = Amp\call(function () use ($pool, $index, $task) {
                                $result = yield $pool->enqueue($task);
                                return $result;
                            });
                        }
                        /* changed to "first()" instead of  "all()" */
                        $results = yield Amp\Promise\first($coroutines);
                        
                        /* commented out shutdown */
                        //yield $pool->shutdown();

                    });
                }`

It works! Could you explain what's happening here please? My understanding is that because the parent code shuts down the pool, it kills all child processes in it too hence me getting the following errors:

**Error 1:** 
```
[20-Jun-2021` 12:34:42 GB] PHP Warning:  stream_socket_client(): Unable to connect to unix:///tmp/amp-parallel-ipc-1d462f323b092068276e.sock (Connection refused) in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 67

[20-Jun-2021 12:34:42 GB] PHP Fatal error:  Could not connect to IPC socket in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 69

[20-Jun-2021 12:34:42 GB] PHP Warning:  stream_socket_client(): Unable to connect to unix:///tmp/amp-parallel-ipc-1d462f323b092068276e.sock (Connection refused) in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 67

[20-Jun-2021 12:34:42 GB] PHP Fatal error:  Could not connect to IPC socket in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 69

[20-Jun-2021 12:34:42 GB] PHP Warning:  stream_socket_client(): Unable to connect to unix:///tmp/amp-parallel-ipc-1d462f323b092068276e.sock (Connection refused) in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 67

[20-Jun-2021 12:34:42 GB] PHP Fatal error:  Could not connect to IPC socket in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 69

[20-Jun-2021 12:34:42 GB] PHP Warning:  stream_socket_client(): Unable to connect to unix:///tmp/amp-parallel-ipc-1d462f323b092068276e.sock (Connection refused) in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 67

[20-Jun-2021 12:34:42 GB] PHP Fatal error:  Could not connect to IPC socket in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 69

[20-Jun-2021 12:34:42 GB] PHP Warning:  stream_socket_client(): Unable to connect to unix:///tmp/amp-parallel-ipc-1d462f323b092068276e.sock (Connection refused) in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 67

[20-Jun-2021 12:34:42 GB] PHP Fatal error:  Could not connect to IPC socket in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 69
```

**Error 2:** 

```
[20-Jun-2021 15:16:33 Europe/London] PHP Fatal error:  Uncaught Amp\Parallel\Sync\ContextPanicError: Uncaught Error in child process or thread with message "Loop stopped without resolving the promise" and code "0"; use Amp\Parallel\Sync\ContextPanicError::getOriginalTrace() for the stack trace in the child process or thread in /home/xxxx/vendor/amphp/parallel/lib/Sync/ExitFailure.php:46

Stack trace:
#0 /home/xxxx/vendor/amphp/parallel/lib/Sync/ExitFailure.php(39): Amp\Parallel\Sync\ExitFailure->createException()

#1 /home/xxxx/vendor/amphp/parallel/lib/Context/Process.php(232): Amp\Parallel\Sync\ExitFailure->getResult()

#2 [internal function]: Amp\Parallel\Context\Process->Amp\Parallel\Context\{closure}()

#3 /home/xxxx/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Amp\Parallel\Sync\ExitFailure))

#4 /home/xxxx/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Amp\Parallel\Sync\ExitFailure))

#5 /home/xxxx/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Amp\Parallel\Sync\ExitFailure))

#6 /home/xxxx/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, '\x00\xF4\x02\x00\x00O:29:"Amp\\...')

#7 /home/xxxx/vendor/amphp/amp/lib/Deferred.php(52): Amp\Promise@anonymous->resolve('\x00\xF4\x02\x00\x00O:29:"Amp\\...')

#8 /home/xxxx/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve('\x00\xF4\x02\x00\x00O:29:"Amp\\...')

#9 /home/xxxx/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('ru', '\x00\xF4\x02\x00\x00O:29:"Amp\\...')

#10 /home/xxxx/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()

#11 /home/xxxx/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()

#12 /home/xxxx/public_html/scripts/cron_temp1.php(254): Amp\Loop::run(Object(Closure))

#13 {main}
  thrown in /home/xxxx/vendor/amphp/parallel/lib/Sync/ExitFailure.php on line 46
  
[20-Jun-2021 15:17:02 GB] PHP Fatal error:  Could not send result to parent; be sure to shutdown the child before ending the parent in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 120

[20-Jun-2021 15:17:29 Europe/London] PHP Fatal error:  Uncaught Amp\Parallel\Sync\ContextPanicError: Uncaught Error in child process or thread with message "Loop stopped without resolving the promise" and code "0"; use Amp\Parallel\Sync\ContextPanicError::getOriginalTrace() for the stack trace in the child process or thread in /home/xxxx/vendor/amphp/parallel/lib/Sync/ExitFailure.php:46

Stack trace:

#0 /home/xxxx/vendor/amphp/parallel/lib/Sync/ExitFailure.php(39): Amp\Parallel\Sync\ExitFailure->createException()

#1 /home/xxxx/vendor/amphp/parallel/lib/Context/Process.php(315): Amp\Parallel\Sync\ExitFailure->getResult()

#2 [internal function]: Amp\Parallel\Context\Process->Amp\Parallel\Context\{closure}()

#3 /home/xxxx/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(0)

#4 /home/xxxx/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 0)

#5 /home/xxxx/vendor/amphp/amp/lib/Deferred.php(52): Amp\Promise@anonymous->resolve(0)

#6 /home/xxxx/vendor/amphp/process/lib/Internal/Posix/Runner.php(40): Amp\Deferred->resolve(0)

#7 /home/xxxx/vendor/amphp/amp/lib/Loop/NativeDriver.php(321): Amp\Process\Internal\Posix\Runner::onProcessEndExtraDataPipeReadable('fu', Resource id #2984, Object(Amp\Process\Internal\Posix\Handle))

#8 /home/xxxx/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.097)

#9 /home/xxxx/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)

#10 /home/xxxx/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()

#11 /home/xxxx/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()

#12 /home/xxxx/public_html/scripts/cron_temp1.php(254): Amp\Loop::run(Object(Closure))

#13 {main}
  thrown in /home/xxxx/vendor/amphp/parallel/lib/Sync/ExitFailure.php on line 46
  
[20-Jun-2021 15:17:46 GB] PHP Fatal error:  Could not send result to parent; be sure to shutdown the child before ending the parent in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 120

[20-Jun-2021 15:17:57 GB] PHP Fatal error:  Could not send result to parent; be sure to shutdown the child before ending the parent in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 120

[20-Jun-2021 15:17:58 GB] PHP Fatal error:  Could not send result to parent; be sure to shutdown the child before ending the parent in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 120

[20-Jun-2021 15:18:14 GB] PHP Fatal error:  Could not send result to parent; be sure to shutdown the child before ending the parent in /home/xxxx/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 120
```

Please help me understand what's the issue here. Thank you!!

**Comment by iamsyh** [comment]
Another note, it doesn't matter if I reduce the number of workers in both the main process and sub-process.

It still errors out using the 2nd code

**Comment by trowski** [comment]
Apologies this issue did not receive any attention when it was posted. As this issue is old, I'm closing it. Please open another issue if you're still interested in assistance or feedback.
