### ISSUE TITLE
The channel closed unexpectedly. Did the context die

### ISSUE THREAD

**Issue by waleedmazhar** [amphp/parallel#81]
Getting error 
```
Fatal error: Uncaught Amp\Parallel\Sync\ChannelException: The channel closed unexpectedly. Did the context die? in /var/www/html/vendor/amphp/parallel/lib/Sync/ChannelledStream.php:68
Stack trace:
#0 [internal function]: Amp\Parallel\Sync\ChannelledStream->Amp\Parallel\Sync\{closure}()
#1 /var/www/html/vendor/amphp/amp/lib/Coroutine.php(74): Generator->send(NULL)
#2 /var/www/html/vendor/amphp/amp/lib/Internal/Placeholder.php(127): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#3 /var/www/html/vendor/amphp/amp/lib/Deferred.php(41): class@anonymous->resolve(NULL)
#4 /var/www/html/vendor/amphp/byte-stream/lib/ResourceInputStream.php(177): Amp\Deferred->resolve()
#5 /var/www/html/vendor/amphp/byte-stream/lib/ResourceInputStream.php(165): Amp\ByteStream\ResourceInputStream->free()
#6 /var/www/html/vendor/amphp/parallel/lib/Sync/ChannelledSocket.php(32): Amp\ByteStream\ResourceInputStream->close()
#7 /var/www/html/vendor/amphp/amp/lib/Loop/NativeDriver.php(101): Amp\Parallel\Sync\ChannelledSocket->close('dz', NULL)
#8 /var/www/html/ in /var/www/html/vendor/amphp/parallel/lib/Sync/ChannelledStream.php on line 68
```

I am using php7.0-zts and running script in cli mode.

**Comment by trowski** [comment]
I'll be happy to help, but I'm going to need more context about what you were doing when you saw that error. I need to see the code creating the context and the code running in the context.

**Comment by kelunik** [comment]
Closing due to inactivity.

**Comment by BasicPro** [comment]
I'm having this same issue under specific conditions, not sure what I'm doing wrong. This happens when I try to call a class static method from a the callable function. But only when the class is defined in a different file than the callable function. I'm thinking it should be a problem on how composer is loading my classes but I don't understand why this happens, the classes are loaded correctly. Some help would be appreciated.

This is how I set the parallel class
```
use Amp\Parallel\Worker;
use Amp\Promise;

class MB_Parallel_Processor {

  public static function process(){

    $processes = ['recommended' => 0, 'high' => 2, 'low' => -2];
    $promises = [];
    foreach ($processes as $process => $input) {
        $promises[$process] = Worker\enqueueCallable('parallel_test', $input);
    }
    return Promise\wait(Promise\all($promises));
  }
}
```
This is my test callable:
```
function parallel_test($input){
  return Test_Static_Class::get_test();
}
```
This is my composer.json file.
```
{
    "require": {
        "amphp/amp": "^2.4",
        "marrouchi/polynomial-regression": "v0.2.1.1",
        "amphp/parallel": "^1.4"
    },
    "autoload": {
        "files": [
            "autoload-functions.php"
        ],
        "classmap": ["inc/"]
    }
}

```
The callable function is in "autoload-functions.php" and the test class is in the inc folder loaded with classmap.

Finally, this is the error dump:
```
2020/06/12 11:27:29 [error] 28487#28487: *4176520 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Amp\Parallel\Sync\ChannelException: The channel closed unexpectedly. Did the context die? in /home/masteringbox.com/wp-content/plugins/masteringbox/vendor/amphp/parallel/lib/Sync/ChannelledStream.php:74
Stack trace:
#0 [internal function]: Amp\Parallel\Sync\ChannelledStream->Amp\Parallel\Sync\{closure}()
#1 /home/masteringbox.com/wp-content/plugins/masteringbox/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(NULL)
#2 /home/masteringbox.com/wp-content/plugins/masteringbox/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#3 /home/masteringbox.com/wp-content/plugins/masteringbox/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve(NULL)
#4 /home/masteringbox.com/wp-content/plugins/masteringbox/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve(NULL)
#5 /home/masteringbox.com/wp-content/plugins/masteringbox/vendor/amphp/amp/lib/Loop/NativeDriver.php(201): Amp\ByteStream" while reading response header from upstream, client: 84.122.211.44, server: www.onlinerecordingstudios.com, request: "POST /wp-json/master/upload/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "www.onlinerecordingstudios.com", referrer: "https://www.onlinerecordingstudios.com/?debug=debug"

```
I'm quite new to using composer autoload so please pardon my ignorance, I'm sure I'm missing something obvious.

Thank you
