### ISSUE TITLE
Fatal error when passing user defined function

### ISSUE THREAD

**Issue by vladimir-vv** [amphp/parallel#83]
In my opinion you are creating very interesting and useful framework.
Thank you!
I'm trying to learn how to use it.

I have troubles with examples:
amphp/parallel/tree/master/examples/worker-pool.php
amphp/parallel/tree/master/examples/worker-pool-simple.php

and I want to pass my function as task:
```php
function fz1($p='zxc') {
  echo __FUNCTION__.' '.$p.PHP_EOL;
  return 'test1';
}
```
`... new CallableTask('fz1', ['http://php.net']) ...`
or
`... $promises[$url] = Worker\enqueueCallable('fz1', $url); ...`

and I'm getting error:
```
PHP Fatal error:  Uncaught Amp\Parallel\Worker\TaskError: Uncaught Error in worker with message "Call to undefined function fz1()" and code "0"; use Amp\Parallel\Worker\TaskError::getWorkerTrace() for the stack trace in the worker in composer/vendor/amphp/parallel/lib/Worker/Internal/TaskFailure.php:61
Stack trace:
#0 composer/vendor/amphp/parallel/lib/Worker/Internal/TaskFailure.php(50): Amp\Parallel\Worker\Internal\TaskFailure->createException()
#1 composer/vendor/amphp/parallel/lib/Worker/TaskWorker.php(134): Amp\Parallel\Worker\Internal\TaskFailure->promise()
#2 [internal function]: Amp\Parallel\Worker\TaskWorker->Amp\Parallel\Worker\{closure}()
#3 composer/vendor/amphp/amp/lib/Coroutine.php(105): Generator->send(Object(Amp\Parallel\Worker\Internal\TaskFailure))
#4 composer/vendor/amphp/amp/lib/Internal/Placehol in composer/vendor/amphp/parallel/lib/Worker/Internal/TaskFailure.php on line 61
```
What am I doing wrong?

**Comment by kelunik** [comment]
@trowski I think it's time to catch the exception and print your comment into a custom exception.
